<?php

namespace Ftt\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultatMedicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatMedicalRepository extends EntityRepository
{
    
    public function getResultatdeChaqueMedecin($idMedecin){
        
        
    }
}
