<?php

namespace Proxies\__CG__\Ftt\BackofficeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Joueur extends \Ftt\BackofficeBundle\Entity\Joueur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'id', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'nomJoueur', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'prenomJoueur', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'carriere', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'dateNaissance', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'club', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'points', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'sexe'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'id', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'nomJoueur', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'prenomJoueur', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'carriere', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'dateNaissance', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'club', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'points', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Joueur' . "\0" . 'sexe'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Joueur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', []);

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function getCarriere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarriere', []);

        return parent::getCarriere();
    }

    /**
     * {@inheritDoc}
     */
    public function getDate_naissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate_naissance', []);

        return parent::getDate_naissance();
    }

    /**
     * {@inheritDoc}
     */
    public function getClub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClub', []);

        return parent::getClub();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setAge($age)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', [$age]);

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function setCarriere($carriere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarriere', [$carriere]);

        return parent::setCarriere($carriere);
    }

    /**
     * {@inheritDoc}
     */
    public function setDate_naissance($date_naissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate_naissance', [$date_naissance]);

        return parent::setDate_naissance($date_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function setClub($club)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClub', [$club]);

        return parent::setClub($club);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoints', []);

        return parent::getPoints();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoints($points)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoints', [$points]);

        return parent::setPoints($points);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance($dateNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomJoueur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomJoueur', []);

        return parent::getNomJoueur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomJoueur($nomJoueur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomJoueur', [$nomJoueur]);

        return parent::setNomJoueur($nomJoueur);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomJoueur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomJoueur', []);

        return parent::getPrenomJoueur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomJoueur($prenomJoueur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomJoueur', [$prenomJoueur]);

        return parent::setPrenomJoueur($prenomJoueur);
    }

}
