terrain:
    path:     /
    defaults: { _controller: "FttBackofficeBundle:Terrain:index" }

terrain_show:
    path:     /{id}/show
    defaults: { _controller: "FttBackofficeBundle:Terrain:show" }

terrain_new:
    path:     /new
    defaults: { _controller: "FttBackofficeBundle:Terrain:new" }

terrain_create:
    path:     /create
    defaults: { _controller: "FttBackofficeBundle:Terrain:create" }
    methods:  POST

terrain_edit:
    path:     /{id}/edit
    defaults: { _controller: "FttBackofficeBundle:Terrain:edit" }

terrain_update:
    path:     /{id}/update
    defaults: { _controller: "FttBackofficeBundle:Terrain:update" }
    methods:  [POST, PUT]

terrain_delete:
    path:     /{id}/delete
    defaults: { _controller: "FttBackofficeBundle:Terrain:delete" }
    methods:  [POST, DELETE]
terrain_delete2:
    path:     /delete
    defaults: { _controller: "FttBackofficeBundle:Terrain:delete2" }

