# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    fos_user.doctrine_registry:
        alias: doctrine
    app.form.registration:
        class: Ftt\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    redirect.after.login:
        class: Ftt\UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router]


    twig.extension.date:
       class: Twig_Extensions_Extension_Date
       tags:
            - { name: twig.extension }


    BackofficeBundle.twig.count_extension:
        class: Ftt\BackofficeBundle\Twig\CountExtension
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"