<?php

namespace Ftt\NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsletterMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterMailRepository extends EntityRepository
{
}
