<?php

namespace Proxies\__CG__\Ftt\BackofficeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Matchs extends \Ftt\BackofficeBundle\Entity\Matchs implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'id', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'typeMatch', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'tournoi', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'date', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'heure', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'resultat', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'terrain', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'joueur1', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'joueur2'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'id', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'typeMatch', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'tournoi', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'date', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'heure', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'resultat', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'terrain', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'joueur1', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Matchs' . "\0" . 'joueur2'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Matchs $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeMatch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeMatch', []);

        return parent::getTypeMatch();
    }

    /**
     * {@inheritDoc}
     */
    public function getTournoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTournoi', []);

        return parent::getTournoi();
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeure', []);

        return parent::getHeure();
    }

    /**
     * {@inheritDoc}
     */
    public function getResultat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResultat', []);

        return parent::getResultat();
    }

    /**
     * {@inheritDoc}
     */
    public function getTerrain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerrain', []);

        return parent::getTerrain();
    }

    /**
     * {@inheritDoc}
     */
    public function getJoueur1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoueur1', []);

        return parent::getJoueur1();
    }

    /**
     * {@inheritDoc}
     */
    public function getJoueur2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoueur2', []);

        return parent::getJoueur2();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeMatch($typeMatch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeMatch', [$typeMatch]);

        return parent::setTypeMatch($typeMatch);
    }

    /**
     * {@inheritDoc}
     */
    public function setTournoi($tournoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTournoi', [$tournoi]);

        return parent::setTournoi($tournoi);
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setHeure($heure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeure', [$heure]);

        return parent::setHeure($heure);
    }

    /**
     * {@inheritDoc}
     */
    public function setResultat($resultat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResultat', [$resultat]);

        return parent::setResultat($resultat);
    }

    /**
     * {@inheritDoc}
     */
    public function setTerrain($terrain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerrain', [$terrain]);

        return parent::setTerrain($terrain);
    }

    /**
     * {@inheritDoc}
     */
    public function setJoueur1($joueur1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoueur1', [$joueur1]);

        return parent::setJoueur1($joueur1);
    }

    /**
     * {@inheritDoc}
     */
    public function setJoueur2($joueur2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoueur2', [$joueur2]);

        return parent::setJoueur2($joueur2);
    }

}
