<?php

namespace Proxies\__CG__\Ftt\BackofficeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paris extends \Ftt\BackofficeBundle\Entity\Paris implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'id', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'matchs', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'cote1', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'cote2', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'rating', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'date', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'idMatch'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'id', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'matchs', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'cote1', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'cote2', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'rating', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'date', '' . "\0" . 'Ftt\\BackofficeBundle\\Entity\\Paris' . "\0" . 'idMatch'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Paris $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatchs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatchs', []);

        return parent::getMatchs();
    }

    /**
     * {@inheritDoc}
     */
    public function getCote1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCote1', []);

        return parent::getCote1();
    }

    /**
     * {@inheritDoc}
     */
    public function getCote2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCote2', []);

        return parent::getCote2();
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', []);

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMatch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMatch', []);

        return parent::getIdMatch();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setMatchs($matchs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatchs', [$matchs]);

        return parent::setMatchs($matchs);
    }

    /**
     * {@inheritDoc}
     */
    public function setCote1($cote1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCote1', [$cote1]);

        return parent::setCote1($cote1);
    }

    /**
     * {@inheritDoc}
     */
    public function setCote2($cote2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCote2', [$cote2]);

        return parent::setCote2($cote2);
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', [$rating]);

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMatch($idMatch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMatch', [$idMatch]);

        return parent::setIdMatch($idMatch);
    }

}
